{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weft.serviceAccountName" . }}
  labels:
    {{- include "weft.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
{{- end }}
